on:
  push:

name: build

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04, r: 'release'}

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get -y install openmpi-bin libpnetcdf-dev libnetcdf-pnetcdf-dev
        shell: /bin/bash {0}

      # - name: pnetcdf
      #   run: |
      #     cd libraries/parallel-netcdf-1.4.0 && ./configure && make
      #   shell: /bin/bash {0}

      - name: make
        run: |
          cd src && make
        shell: /bin/bash {0}
