on:
  push:

name: build

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    env:
      PNETCDF_VERSION: 1.12.1
      NETCDF_DIR: ${{ github.workspace }}/..
      NETCDF_HOME: ${{ github.workspace }}/..

    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04, r: 'release'}

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install mpich libmpich-dev libhdf5-mpich-dev libcurl4-openssl-dev bzip2 libsnappy-dev libblosc-dev libzstd-dev
          echo "Download and build PnetCDF version ${PNETCDF_VERSION}"
          wget https://parallel-netcdf.github.io/Release/pnetcdf-${PNETCDF_VERSION}.tar.gz
          tar -xzf pnetcdf-${PNETCDF_VERSION}.tar.gz
          pushd pnetcdf-${PNETCDF_VERSION}
          ./configure --prefix $NETCDF_DIR --enable-shared --disable-fortran --disable-cxx
          make -j 2
          make install
        shell: /bin/bash {0}

      # - name: pnetcdf
      #   run: |
      #     cd libraries/parallel-netcdf-1.4.0 && ./configure && make
      #   shell: /bin/bash {0}

      - name: make
        run: |
          cd src && ./make.sh
        shell: /bin/bash {0}
